### ISSUE TITLE
Initiële lijst met NL organisaties die een OSPO hebben

### ISSUE THREAD

**Issue by Jonasvdbo** [ospo-nl/kennisbank#12]

**Comment by nicorikken** [comment]
Idee:

1. Startpunt lijst opzetten
2. Andere organisaties uitnodigen zich toe te voegen aan de lijst d.m.v. een pull-request

**Comment by nicorikken** [comment]
Zie #30 voor een start

**Comment by marcvanandel** [comment]
Punt 2 zou op dezelfde pagina toegevoegd kunnen worden, denk ik? Dus een kopje 'Meedoen' oid?

Verder is dit issue klaar, niet?

**Comment by RietveldBLD** [comment]
denk ik ook. Sluit hem wel af, als het nodig is -> heropenen
