### ISSUE TITLE
Support.md

### ISSUE THREAD

**Issue by Jonasvdbo** [ospo-nl/kennisbank#17]

**Comment by Jonasvdbo** [comment]
Zie: https://github.com/ospo-nl/kennisbank/blob/main/docs/Community/SUPPORT.md

**Comment by marcvanandel** [comment]
Wat mij betreft, is dit een prima begin ... welke ik nog verder heb aangevuld met #28 . 

M.a.w. een goed begin en nu gewoon verder ontwikkelen? Sluit jij zelf dit issue af? (en anders doen wij dat in jouw afwezigheid 😜 )
