### ISSUE TITLE
Code of conduct.md

### ISSUE THREAD

**Issue by Jonasvdbo** [ospo-nl/kennisbank#18]

**Comment by Jonasvdbo** [comment]
Zie: https://github.com/ospo-nl/kennisbank/blob/main/docs/Community/Code%20of%20Conduct.md

**Comment by Jonasvdbo** [comment]
@marcvanandel heeft ook een aanzet gedaan voor CODE_OF_CONDUCT.md: https://github.com/ospo-nl/.github/blob/contributing/CONTRIBUTING.md Gezien deze verder uitgewerkt is, zou ik zeggen dat we deze pakken om verder uit te werken.

@marcvanandel ik heb jou nu ook even assignee van deze task gemaakt. Vervang jij tzt de CODE_OF_CONDUCT.md: in https://github.com/ospo-nl/kennisbank/blob/main/docs/Community/Code%20of%20Conduct.md?

**Comment by marcvanandel** [comment]
Zie #28
