### ISSUE TITLE
Github.io opzetten

### ISSUE THREAD

**Issue by Jonasvdbo** [ospo-nl/kennisbank#2]

**Comment by marcvanandel** [comment]
'k Heb alvast een logo bedacht 😁 Het origineel heb ik ook (in .xcf van GIMP) maar die mag ik hier niet uploaden.. Die komt tzt wel in een repo terecht 😉 

![Image](https://user-images.githubusercontent.com/2315396/217199263-0e5db867-3418-486c-89fd-68a7e7c37ed0.png)

**Comment by nicorikken** [comment]
@RietveldBLD ik dacht MKdocs te gaan gebruiken met https://squidfunk.github.io/mkdocs-material/ dat rendert wel prima en wordt ook door andere projecten gebruikt. Had jij dat ook in gedachten, of zag je meer iets anders voor je?

**Comment by RietveldBLD** [comment]
@nicorikken ik zat vanmiddag even te stoeien net Github docs en dat dwingt ons gelijk in de richting van het instelling van de Organisation. Prima voorstel

**Comment by marcvanandel** [comment]
MkDocs-Material heb ik ook gebruikt voor een ander open source project: [SensRNet](https://kadaster-labs.github.io/sensrnet-home/) 😉

**Comment by nicorikken** [comment]
@RietveldBLD dat was eenvoudiger dan ik gedacht had. #27 Documentatie opgepakt vanaf https://squidfunk.github.io/mkdocs-material/getting-started/ Ik heb ervoor gekozen om Poetry te gebruiken om de dependencies te managen, dan heb ik zekerheid over version pinning.

**Comment by marcvanandel** [comment]
![ospo-nl-logo-vlag](https://user-images.githubusercontent.com/2315396/218057176-8caaa35d-3aee-4e52-bfa7-944330357f7e.png)

😄 wat dachten jullie van dit logo? 😁

**Comment by RietveldBLD** [comment]
@marcvanandel de versie zonder rood-wit-blauw staat me toch meer aan :-)

**Comment by marcvanandel** [comment]
OK. Onder elkaar is wellicht wel mooier? (meer vierkant) 



![Image](https://user-images.githubusercontent.com/2315396/218390499-10aa3fca-9726-418c-815d-63c04083dc0a.png)

**Comment by marcvanandel** [comment]
Gewoon omdat het kan 😄 

![Image](https://user-images.githubusercontent.com/2315396/220111849-4411fd2f-f61f-4013-83be-d7c00f32a21f.png)

**Comment by nicorikken** [comment]
Ik heb ook eerder zo'n OSPO logo gebruikt met het logo van het Open Source Initiative als de 'O', maar vanwege trademark ben ik huiverig om dit in te voeren. Maar een simpel typografisch logo lijkt mij prima.

**Comment by marcvanandel** [comment]
Hmm... scherp! Daar heb ik eigenlijk niet over nagedacht 🙈

**Comment by RietveldBLD** [comment]
A, dat moeten we voorkomen. Dus dan maar zonder open O?

**Comment by marcvanandel** [comment]
https://commons.wikimedia.org/wiki/File:Opensource.svg is Creative Commons Attribution licensed:

> You are free:
>   - **to share** – to copy, distribute and transmit the work
>   - **to remix** – to adapt the work
>
> Under the following conditions:
>   - **attribution** – You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

**Comment by marcvanandel** [comment]
OK. Het logo wordt in een apart issue opgepakt (#35) Als we PR https://github.com/ospo-nl/.github/pull/1 mergen, is dit issue dan verder klaar ... voor dit eerste moment?

**Comment by marcvanandel** [comment]
Merged! Dan is dit issue voor dit moment wel klaar. Nieuwe features pakken we met nieuwe issues op. OK? (weinig opties, want ik sluit 'm direct met dit comment 😆 )
