### ISSUE TITLE
Type licenties.md

### ISSUE THREAD

**Issue by Jonasvdbo** [ospo-nl/kennisbank#21]

**Comment by Jonasvdbo** [comment]
Zie: https://github.com/ospo-nl/kennisbank/blob/main/docs/Best%20practices/Type%20licenties.md

**Comment by marcvanandel** [comment]
Ik vind spaties in de structuur ... erg lelijk! Dat worden in de URL allemaal `%20` ...

**Comment by marcvanandel** [comment]
Is dit nieuwe content? Staat dit niet al ergens (of veelvuldig) beschreven? Of is dit een samenvatting van andere content? Ik mis in ieder geval verwijzingen naar andere informatie of van welke informatie deze pagina de samenvatting is ...
