### ISSUE TITLE
Casus OpenStad beschrijven volgens checklist

### ISSUE THREAD

**Issue by nicorikken** [ospo-nl/kennisbank#47]

**Comment by evavansloten** [comment]
@nicorikken wil je dit nog doen?

**Comment by evavansloten** [comment]
@MauriceHendriks wil je dit nog doen?

**Comment by MauriceHendriks** [comment]
Het is me niet gelukt de mensen achter OpenStad te bereiken hiervoor.

**Comment by jgroenen** [comment]
Ik sprak gisteren nog iemand van OpenStad, waar vind ik de checklist?
