### ISSUE TITLE
Over_ons.md

### ISSUE THREAD

**Issue by Jonasvdbo** [ospo-nl/kennisbank#5]
met apart contribute.md?

**Comment by marcvanandel** [comment]
Yup. Met een aparte CONTRIBUTING.md ... Work-in-progress in https://github.com/ospo-nl/.github/pull/1 😉

**Comment by Jonasvdbo** [comment]
@marcvanandel  Top, ik had ook al kleine aanzet gedaan voor CONTRIBUTING.md Zie: https://github.com/ospo-nl/kennisbank/blob/main/docs/Community/CONTRIBUTING.md 

Ik zie dat jij al veel verder bent, dus laten we jou CONTRIBUTING.md versie als leidend nemen.

**Comment by marcvanandel** [comment]
Zie #28
