### ISSUE TITLE
Afspraken over fileformats e.d.

### ISSUE THREAD

**Issue by MauriceHendriks** [ospo-nl/kennisbank#57]
Dingen die ik als linux gebruiker fijn zou vinden:
- Geen spaties in padnamen
- Alle bestanden als UTF-8 LF zonder BOM (dus zonder CR).

Daarmee voorkomen we ook diffs die triggeren op futiliteiten zoals einde regel karakters.

**Comment by marcvanandel** [comment]
Agree! Dit werkt in URLs ook erg slecht ...

**Comment by marcvanandel** [comment]
We spreken af dat je bij je volgende PR je houdt aan bovenstaand voorstel. Anders krijg je commentaar 😉

**Comment by marcvanandel** [comment]
Interesting background and tips:

- [Blog: Mind the End of Your Line](https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/)
- [GitHub Help on Line Endings](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)

BOM lijkt niet (echt) een probleem te zijn .. ? 🤔
