### ISSUE TITLE
Contribute.MD template

### ISSUE THREAD

**Issue by Jonasvdbo** [ospo-nl/kennisbank#7]

**Comment by Jonasvdbo** [comment]
Eerste aanzet om verder aan te vullen: https://github.com/ospo-nl/kennisbank/blob/main/docs/Community/CONTRIBUTING.md

**Comment by Jonasvdbo** [comment]
@marcvanandel heeft ook een aanzet gedaan voor CONTRIBUTING.md: https://github.com/ospo-nl/.github/blob/contributing/CONTRIBUTING.md 

Gezien deze verder is, zou ik zeggen dat we deze voor nu leidend laten zijn. 

@marcvanandel ik heb jou nu ook even assigne van deze tasks gemaakt.

**Comment by marcvanandel** [comment]
@Jonasvdbo en @nicorikken , in de CONTRIBUTING guide templates wordt gesuggereerd om een alternatieve kanaal als email te gebruiken in geval van gevoelige informatie. Is het een idee om daar voor nu jullie ospo mailadres voor te gebruiken? Kdstr heeft nog geen mailadres en BLD ... weet ik niet? Het lijkt mij op zich wel een goed idee om zo'n alternatieve route beschikbaar te hebben voor het geval een issue toch iets te openbaar is voor gevoelige info ...

**Comment by marcvanandel** [comment]
Zie #28
