### ISSUE TITLE
ZBO-lijstje klopt niet

### ISSUE THREAD

**Issue by adgerrits** [ospo-nl/kennisbank#79]
Op de pagina https://ospo-nl.github.io/kennisbank/bronnen/nederlands-overzicht/ staat een lijst met organisaties die ZBO's zouden zijn. Voor 3 daarvan klopt dat niet. Het Nationaal Archief valt onder het Ministerie van Onderwijs, Cultuur en Wetenschap, Alliander is een bedrijf, Common Ground is een programma.

**Comment by marcvanandel** [comment]
@adgerrits , is het zo (als in PR #85 - zie [files changed](https://github.com/ospo-nl/kennisbank/pull/85/files)) beter?

**Comment by adgerrits** [comment]
Niet aleen beter, maar wat mij betreft helemaal goed.

**Comment by marcvanandel** [comment]
Dan sluit ik het issue af. Als er nog meer opmerkingen of verbeteringen mogelijk zijn, dan horen we 't wel! 😄 Bedankt voor deze!!
