### ISSUE TITLE
Voorstel om public domain expliciet te noemen onder open-source-software-licenties

### ISSUE THREAD

**Issue by RoelvandenBerg** [ospo-nl/kennisbank#83]
Los van de licenties die [hier](https://ospo-nl.github.io/kennisbank/best-practices/open-source-software-licenties/) beschreven staan is er ook nog de mogelijkheid die sommige developers wordt gehanteerd is om software expliciet in de [public domain](https://en.wikipedia.org/wiki/Public-domain_software) te plaatsen. Enige lastige hiervan is dat dit volgens de NLse/EU wetgeving mogelijk? [niet](https://nl.wikipedia.org/wiki/Publiek_domein#Expliciet_publiek_domein) [kan](https://creativecommons.nl/publiek-domein/). Dus sowieso niet wenselijk om zelf te doen, maar het kan relevant zijn om wel te noemen dat dit een mogelijkheid is en advies om daar mee om te gaan. Een voorbeeld van software die door de makers in het public domain is geplaatst is bijvoorbeeld [sqlite](https://www.sqlite.org/copyright.html). 

Het kan zijn dat met deze noot gedoeld wordt op public domain software: 

> Andersom kan broncode ook openbaar worden gemaakt zonder OSS licentie. Daarmee blijft de broncode auteursrechtelijk beschermd en kan het dus niet worden hergebruikt, aangepast of worden gedeeld. Openbaarmaking geeft wel inzicht in de broncode.

Als dat zo is, zou ik dit dan wel expliciet noemen. 

En voor de duidelijkheid: ik ben dus geen jurist.

**Comment by marcvanandel** [comment]
@MauriceHendriks , heb jij hier een kijk op?

**Comment by MauriceHendriks** [comment]
> Het kan zijn dat met deze noot gedoeld wordt op public domain software:

Dat is niet wat daar bedoeld wordt. Dat gaat voort op dit stukje uit de handleiding:

> Alles wat je maakt valt standaard onder het auteursrecht (copyright) als onderdeel van het intellectueel eigendomsrecht (IE-recht) en mag dus niet zomaar door derden, zonder jouw toestemming, worden (her)gebruikt of gedeeld

Wat een open source licentie doet is een verbruikerslicentie afgeven over de broncode waarbij de beperkingen die voortvloeien uit het auteursrecht worden opgeheven, maar niet het auteursrecht zelf.

Wat met public domain wordt bedoeld is dat je ook het auteursrecht zelf opgeeft en daarmee verklaart dat het auteursrecht bij niemand ligt en er dus ook geen enkele beperkingen meer zijn in het gebruik van de broncode. Er is niemand meer die rechtsgeldig mogelijke beperkingen kan handhaven. De broncode is van niemand meer en daarmee in dit geval van iedereen.

De BSD-0 licentie komt het dichts in de buurt van het public domain, omdat BSD-0 ook geen naamsvermeldingseis bevat. Maar ook hier is het verschil dat bij een BSD-0 het copyright bij de oorspronkelijke auteur in tact blijft

Oftewel:
- Alle OSS-licenties respecteren de copyright van de oorspronkelijke auteur
- Met public domain heft de auteur zijn eigen copyright op ten behoeve van het publieke domein

@RoelvandenBerg Het lijkt me goed die optie alsnog te vermelden op de licentiepagina.

**Comment by MauriceHendriks** [comment]
Done
