### ISSUE TITLE
Best practices over Developer Certificate of Origin (DCO)

### ISSUE THREAD

**Issue by Jonasvdbo** [ospo-nl/kennisbank#9]

**Comment by Jonasvdbo** [comment]
Zie: https://github.com/ospo-nl/kennisbank/blob/main/docs/Best%20practices/Developer%20Certificate%20of%20Origin%20(DCO).md

**Comment by marcvanandel** [comment]
D'r zit nog een typo in (ergens staat nog 'Developer Certificate or Origin') ... en er wordt nog Alliander genoemd. Ik denk dat we twee zaken hier willen publiceren:

1. De DCO voor OSPO-NL
2. Hoe maak ik een DCO voor mijn eigen organisatie?

In de CONTRIBUTING guide heb ik bij de [Attribution](https://ospo-nl.github.io/kennisbank/Community/CONTRIBUTING/#attribution) beschreven hoe ik 'm gemaakt heb en aangegeven hoe je dat zelf zou kunnen doen. Ik denk dat we ook nog een lijstje van 'How to's gaan maken waar dat in wordt beschreven.

De vraag voor dit issue is hoe we dat willen doen voor de DCO?
